import { HumonicsClient } from '@humonics/sdk';
import { Keypair } from '@stellar/stellar-sdk';
import type { ZKProof } from '@humonics/sdk';

const client = new HumonicsClient({ network: 'testnet' });

// Keypair should be loaded from a secure secret store — never hardcoded
const keypair = Keypair.fromSecret(process.env['STELLAR_SECRET_KEY']!);

// zkProof generated by the zk-circuits package
const zkProof: ZKProof = {
  pi_a: ['...'],
  pi_b: [['...'], ['...']],
  pi_c: ['...'],
  protocol: 'groth16',
  curve: 'bn128',
};

const cert = await client.issue({
  contentHash: 'a'.repeat(64), // SHA-256 hex of your content
  zkProof,
  did: `did:stellar:${keypair.publicKey()}`,
  contentType: 'text',
  keypair,
});

console.log('Certificate issued:', cert.id);
console.log('Transaction:', cert.txHash);

// Revoke later if needed
await client.revoke(cert.id, keypair);
console.log('Certificate revoked');
